name: Buccannerdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39199
title: Buccaneer design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b09'
    - '#aa8b5c'
    - '#2b2b2b'
    - '#ede9e6'
    - '#c3bfb4'
  brandStrength: 0.773441445780918
  lightness: 0.1480446453206241
  saturation: 0.3879040195606649
  rhythmicContrast: 0.7637281788047403
purpose: []
